name: Build KubePoke

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -o kubepoke-${{ matrix.goos }}-${{ matrix.goarch }} ./bin/kubepoke

      - name: Archive the build
        run: |
          tar -czvf kubepoke-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz kubepoke-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubepoke-${{ matrix.goos }}-${{ matrix.goarch }}
          path: kubepoke-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
